services:
  - type: worker
    name: telegram-bot-mediator
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    disk:
      name: telegram-bot-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/var/data/telegram-bot.db
      - key: BotSettings__Token
        sync: false
      - key: BotSettings__AdminTelegramId
        value: "1170552524"
