services:
  - type: worker
    name: telegram-bot-mediator
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: BotSettings__Token
        sync: false
      - key: BotSettings__AdminTelegramId
        value: "1170552524"
